# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget_Files = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_Files.setGeometry(QtCore.QRect(10, 50, 781, 181))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listWidget_Files.setFont(font)
        self.listWidget_Files.setObjectName("listWidget_Files")
        self.lbl_File = QtWidgets.QLabel(self.centralwidget)
        self.lbl_File.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_File.setFont(font)
        self.lbl_File.setObjectName("lbl_File")
        self.btn_DeleteFile = QtWidgets.QPushButton(self.centralwidget)
        self.btn_DeleteFile.setGeometry(QtCore.QRect(700, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_DeleteFile.setFont(font)
        self.btn_DeleteFile.setObjectName("btn_DeleteFile")
        self.lbl_Data = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Data.setGeometry(QtCore.QRect(10, 250, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_Data.setFont(font)
        self.lbl_Data.setObjectName("lbl_Data")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 230, 841, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.table_Data = QtWidgets.QTableWidget(self.centralwidget)
        self.table_Data.setGeometry(QtCore.QRect(10, 290, 781, 271))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.table_Data.setFont(font)
        self.table_Data.setObjectName("table_Data")
        self.table_Data.setColumnCount(0)
        self.table_Data.setRowCount(0)
        self.btn_DeleteRow = QtWidgets.QPushButton(self.centralwidget)
        self.btn_DeleteRow.setGeometry(QtCore.QRect(700, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_DeleteRow.setFont(font)
        self.btn_DeleteRow.setObjectName("btn_DeleteRow")
        self.btn_DeleteCol = QtWidgets.QPushButton(self.centralwidget)
        self.btn_DeleteCol.setGeometry(QtCore.QRect(570, 250, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_DeleteCol.setFont(font)
        self.btn_DeleteCol.setObjectName("btn_DeleteCol")
        self.btn_Export = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Export.setGeometry(QtCore.QRect(700, 570, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_Export.setFont(font)
        self.btn_Export.setObjectName("btn_Export")
        self.btn_AddFile = QtWidgets.QPushButton(self.centralwidget)
        self.btn_AddFile.setGeometry(QtCore.QRect(600, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_AddFile.setFont(font)
        self.btn_AddFile.setObjectName("btn_AddFile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "App"))
        self.lbl_File.setText(_translate("MainWindow", "Files"))
        self.btn_DeleteFile.setText(_translate("MainWindow", "Delete File"))
        self.lbl_Data.setText(_translate("MainWindow", "Data"))
        self.btn_DeleteRow.setText(_translate("MainWindow", "Delete Row"))
        self.btn_DeleteCol.setText(_translate("MainWindow", "Delete Column"))
        self.btn_Export.setText(_translate("MainWindow", "Export"))
        self.btn_AddFile.setText(_translate("MainWindow", "Add File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
